// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcMufEuhD-NZMuITf2ntRRu8fJc_0w7UQ',
    appId: '1:582102451528:web:dadc5524ece9c68db95f7d',
    messagingSenderId: '582102451528',
    projectId: 'movie-app-f3a56',
    authDomain: 'movie-app-f3a56.firebaseapp.com',
    storageBucket: 'movie-app-f3a56.appspot.com',
    measurementId: 'G-XXGZP2R1SH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq3fh7rP5rC3kC8mNw_jPkbdZU3tgoMY8',
    appId: '1:582102451528:android:19e36360b5cecb01b95f7d',
    messagingSenderId: '582102451528',
    projectId: 'movie-app-f3a56',
    storageBucket: 'movie-app-f3a56.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbW3YDPknFuTBPFWs4fvdJeJXu8j0WXYo',
    appId: '1:582102451528:ios:fe74f292a4689e6fb95f7d',
    messagingSenderId: '582102451528',
    projectId: 'movie-app-f3a56',
    storageBucket: 'movie-app-f3a56.appspot.com',
    iosClientId: '582102451528-u0361g9glftv8r041hlpn0kd1jnftvta.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbW3YDPknFuTBPFWs4fvdJeJXu8j0WXYo',
    appId: '1:582102451528:ios:fe74f292a4689e6fb95f7d',
    messagingSenderId: '582102451528',
    projectId: 'movie-app-f3a56',
    storageBucket: 'movie-app-f3a56.appspot.com',
    iosClientId: '582102451528-u0361g9glftv8r041hlpn0kd1jnftvta.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieApp',
  );
}
